### ISSUE TITLE
webpack 5 BREAKING CHANGE warning

### ISSUE THREAD

**Issue by pixelplanetdev** [ttag-org/ttag-webpack-plugin#16]
I am getting the following depreciation warnings and errors in webpack 5.10:

(node:19535) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'map' is deprecated)
(node:19535) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

**Comment by arananegra** [comment]
I'm also having this problem and it seems that this library it's not maintained .... 😞  It's sad because I can't find any other alternative

**Comment by pixelplanetdev** [comment]
After trying a lot, i ended up just using the babel plugin and it works fine.
The ttag-webpack-plugin doesn't give you any advantage anyway, because it still compiles every single asset for every single language separately.

You can set it up with the babel-plugin, like here
https://ttag.js.org/blog/2018/09/05/hardcore-webpack-setup.html
and here is how i did it (i also have lots of other stuff going on, so idk if reading it helps much):
https://github.com/pixelplanetdev/pixelplanet/blob/master/webpack.config.client.babel.js
I'm checking which .po files are available and then create a webpack config array with all of them and compile it with parallel-webpack.

I highly suggest going through the pain to set everything up with ttag, it is really awesome to work with once you got it set up.

**Comment by AlexMost** [comment]
Hi @pixelplanetdev! The main idea of ttag-webpack-plugin was to remove all those steps from the manual setup, but unfortunately, the current implementation of that plugin requires to be rethought. Any suggestions on how we can improve webpack integration process will be appreciated!
