### ISSUE TITLE
[Compatibility] Not working well with `vue-loader`

### ISSUE THREAD

**Issue by eavae** [ttag-org/ttag-webpack-plugin#7]
I am trying to use this plugin with `vue-loader`, but seems like not working well with that.  The compiler fails with `Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.`

I spent hours to go through the code but didn't find the root cause.  Could anyone help me to figure out the problem or fix it?

I created the test cases in [here](https://github.com/eavae/ttag-webpack-plugin).

**Comment by AlexMost** [comment]
Hi @eavae! This is an experimental plugin, webpack API is not trivial, and not sure that we will continue to support this plugin. Anyway, you can try to configure webpack with `babel-plugin-ttag`. Here is a doc about how you can do that (both precompile translations or inject at a runtime) - https://ttag.js.org/blog/2018/09/05/hardcore-webpack-setup.html

**Comment by eavae** [comment]
Good to know, Thanks a lot.
